### ISSUE TITLE
library description

### ISSUE THREAD

**Issue by gordonaa** [MaayanLab/enrichr_issues#10]
Can you please add a description of each library to the website. I found the description in the supplementary data from the 2016 paper but it would be much more useful on the website.

**Comment by maxim-k** [comment]
@gordonaa most libraries have descriptions. To view them hover over **ⓘ** icon in top right corner of a library card.


![lib_desc](https://user-images.githubusercontent.com/5928795/108898892-c51e7400-75e5-11eb-8819-81d09461c57d.png)

**Comment by gordonaa** [comment]
Thanks! Any chance you could also add them to the library page of the website? 
![image](https://user-images.githubusercontent.com/18355618/108900242-423def00-75ce-11eb-9ec8-83499bcce74d.png)

**Comment by simonmfr** [comment]
I'd support this Idea. For several libraries the exact source is not clear, and the link doesn't help much. For instance I was wondering about the source of Allen_Brain_Atlas_10X_scRNA containing mouse and human cell types. The [Yao 2021 Cell paper](https://www.sciencedirect.com/science/article/abs/pii/S0092867421005018) only studied mouse cell types to my knowledge.

Much appreciated!

**Comment by alnf** [comment]
I have similar request - is it possible to get information/source code on particular libraries creation? For example, I'm interested in GTEx Heart 20-29 vs 30-39 Down. Which samples did you take to generate the set, did you do data pre-processing, did you remove any outliers? Why subselect down/upregulated separately? Also, how to interpret comparison exactly? Are those genes downregulated in 30-39 exactly?

It's very hard to report finding in the paper if we can't explain how the gene set was generated exactly. I think EnrichR tool is widely used and it will certainly benefit further from the library specific info.

**Comment by AviMaayan** [comment]
Hi @alnf the description of how the aging library from GTEx was created is in this paper: https://academic.oup.com/nar/article/50/W1/W697/6582159 under the subtitle:
Gene expression signatures of aging from GTEx
We are working towards creating ETL Appyters for each library, but this will take some time: https://appyters.maayanlab.cloud/#/?q=etl

**Comment by josruirod** [comment]
Hi, 

First of all thansk for the huge work in this awesome project that is widely-used.
Any new on the subject of this issue (sorry if it's not good practice to use an old one, I did because it was still open)

It's been more than 3 years with this issue, and getting info on the libraries, even a one line description, seems to be surprisingly difficult?
I understand there's info on the supplementary data of the paper, and also in the "?" icon after the analyses. There also seemed to be some plans for sharing appyters. However, I think the most frequent need would not to redo databases or comprehensively get info, but just a quick glance on a one-line two-line description of the database. Particularly useful also when using any of the many wrappers of enrichr. 

Similar to the suggestion above, I agree the ideal situation would be to at least have some kind of quick description in the Libraries section of the webpage.

In any case thanks for the support and the tools

**Comment by hlnicholls** [comment]
Hi all, thank you for developing enrichr, it is hugely helpful and a very comprehensive resource.

I am just following-up on this as I went looking for the definition/information on 'GTEx Tissues V8 2023'. However, hoovering over the ⓘ icon doesn't show anything. 

Is there somewhere that I can find the definition behind this source or would it be safe to assume it is just the tissue that is generally most significantly expressed for input genes (regardless of up or down rergulated expression)?

Thank you for your help!

**Comment by AviMaayan** [comment]
Hi @hlnicholls to create the "GTEx Tissues V8 2023" we downloaded the bulk RNA-seq tissue data from GTEx and then normalized the matrix. Then we computed Z-scores for each row (gene) and took the top 100 up genes for each group of samples as the gene set.
