### ISSUE TITLE
Need more information

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [MaayanLab/enrichr_issues#86]
This is not a bug, but we are looking for more information about this collection: "ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X ".

There isn't a lot of information about this collection here: https://maayanlab.cloud/Enrichr/#libraries

Can you please share an official description of this collection ?

**Comment by AviMaayan** [comment]
The ENCODE and ChEA consensus library was created from the original ChEA and ENCODE libraries described in the 2013 paper. In the ENCODE and ChEA libraries the same TF can have multiple entries because the TF was profiled in different cell lines, cell types and tissues, under different conditions and by different labs. The consensus library only has a maximum of two entries per TF, one from ENCODE and one from ChEA. To create these entries we used set intersection to combine the targets for each TF from each library into one set. The intersection is conditional, it depends on how many entries are there for each TF. In other words, the intersection level may be different for each TF. For example, if a TF in ChEA has 5 entries, the consensus set may be composed of genes that are in at least two sets.

**Comment by Krithika-Bhuvan** [comment]
Great thank you !
